FROM public.ecr.aws/lambda/python:3.12@sha256:517bcc7dc1a3ba62e324961c1563cc54a2bd6dc1060188f9d376211ecb7b2926 AS ffmpeg
ARG FFMPEG_VERSION=7.1.1
ARG FFMPEG_SHA256=733984395e0dbbe5c046abda2dc49a5544e7e0e1e2366bba849222ae9e3a03b1
RUN dnf install -y gcc make glibc-static tar xz && dnf clean all \
    && curl --fail --silent --show-error --location --retry 3 \
       "https://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.xz" -o /tmp/ffmpeg-source.tar.xz \
    && echo "$FFMPEG_SHA256  /tmp/ffmpeg-source.tar.xz" | sha256sum --check - \
    && mkdir /tmp/ffmpeg && tar -xJf /tmp/ffmpeg-source.tar.xz --strip-components=1 -C /tmp/ffmpeg \
    && cd /tmp/ffmpeg && ./configure --prefix=/opt/ffmpeg \
       --disable-autodetect --disable-debug --disable-doc --disable-network --disable-x86asm \
       --disable-shared --enable-static --extra-ldflags=-static --disable-everything \
       --enable-ffmpeg --enable-ffprobe --disable-avdevice \
       --enable-decoder=h264,hevc --enable-parser=h264,hevc --enable-demuxer=mov \
       --enable-muxer=rawvideo --enable-encoder=rawvideo --enable-protocol=file,pipe \
       --enable-filter=buffer,buffersink,extractplanes,scale,format,split,hstack,setpts,showinfo,null \
    && make -j2 && make install \
    && cp COPYING.LGPLv2.1 /opt/ffmpeg/LICENSE.txt \
    && cp /tmp/ffmpeg-source.tar.xz /opt/ffmpeg/source.tar.xz

FROM public.ecr.aws/lambda/python:3.12@sha256:517bcc7dc1a3ba62e324961c1563cc54a2bd6dc1060188f9d376211ecb7b2926
COPY --from=ffmpeg /opt/ffmpeg/bin/ffmpeg /opt/ffmpeg/bin/ffprobe /usr/local/bin/
COPY --from=ffmpeg /opt/ffmpeg/LICENSE.txt /opt/ffmpeg/source.tar.xz /opt/ffmpeg/
COPY infra/runtime-requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir --no-compile --require-hashes -r /tmp/requirements.txt --target /var/task \
    && rm /tmp/requirements.txt
ARG NOSTROBE_WHEEL_URL=https://github.com/rahul-software-dev/hazardtrack/releases/download/v0.1.0/nostrobe-0.1.0-py3-none-any.whl
ARG NOSTROBE_WHEEL_SHA256=56bf633697d178fed428be2276e26bfebd4ba33cc40b61a1fe4e538a96ffe92e
RUN curl --fail --silent --show-error --location --retry 3 "$NOSTROBE_WHEEL_URL" \
       -o /tmp/nostrobe-0.1.0-py3-none-any.whl \
    && echo "$NOSTROBE_WHEEL_SHA256  /tmp/nostrobe-0.1.0-py3-none-any.whl" | sha256sum --check - \
    && pip install --no-cache-dir --no-compile --no-deps /tmp/nostrobe-*.whl --target /var/task \
    && rm /tmp/*.whl
COPY infra/lambda/*.py /var/task/
ENV NUMBA_CACHE_DIR=/tmp/numba MPLCONFIGDIR=/tmp/matplotlib
CMD ["handler.handler"]
